language: node_js
node_js:
    - "4.2"
    - "5"

notifications:
  irc:
    channels:
      - "irc.freenode.org#wikimedia-services"
    on_success: change
    on_failure: always

before_install:
  - sudo apt-get update && sudo apt-get install -qq openjdk-7-jre-headless
before_script: 'npm install -g istanbul && npm install -g mocha'
script:  istanbul cover node_modules/.bin/_mocha -- -R spec && (npm run-script coveralls || exit 0)
